export const CLASS_VALIDATOR_EMAIL_VALIDATOR_DI_TOKEN = Symbol(
  "CLASS_VALIDATOR_EMAIL_VALIDATOR_DI_TOKEN",
);

export const BCRYPT_PASSWORD_HASHER_DI_TOKEN = Symbol(
  "BCRYPT_PASSWORD_HASHER_DI_TOKEN",
);
